# Generated by Django 5.1 on 2024-12-29 20:35

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaleventparticipation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaleventparticipation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='field',
            field=models.CharField(max_length=200, null=True, verbose_name='Направление проекта'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='course_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер курса'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='faculty',
            field=models.CharField(max_length=200, null=True, verbose_name='Название факультета'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='university',
            field=models.CharField(max_length=200, null=True, verbose_name='Название ВУЗа'),
        ),
        migrations.AddField(
            model_name='project',
            name='field',
            field=models.CharField(max_length=200, null=True, verbose_name='Направление проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(null=True, related_name='projects', to='portfolio.student', verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер курса'),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(max_length=200, null=True, verbose_name='Название факультета'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(max_length=200, null=True, verbose_name='Название ВУЗа'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Название мероприятия')),
                ('field', models.CharField(max_length=200, null=True, verbose_name='Направление проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание мероприятия')),
                ('address', models.CharField(max_length=300, null=True, verbose_name='Адрес проведения')),
                ('students', models.ManyToManyField(null=True, related_name='events', to='portfolio.student', verbose_name='Участники')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Название мероприятия')),
                ('field', models.CharField(max_length=200, null=True, verbose_name='Направление проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание мероприятия')),
                ('address', models.CharField(max_length=300, null=True, verbose_name='Адрес проведения')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical event',
                'verbose_name_plural': 'historical events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='EventParticipation',
        ),
        migrations.DeleteModel(
            name='HistoricalEventParticipation',
        ),
    ]
